# Generated by Django 5.0.2 on 2024-09-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='createed_at',
            new_name='created_at',
        ),
    ]
